---

name: Disk-Space-Check

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '**/*.md'
      - .gitignore
      - ./meta/main.yml

  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '**/*.md'
      - .gitignore

jobs:
  storage-check:
    runs-on: ubuntu-latest
    steps:
      - name: Show disk usage
        run: df -h

      - name: Top-level directories
        run: du -h -d1 / | sort -hr | head -n 20

      - name: Detailed file sizes
        run: find / -type f -exec du -h {} + 2>/dev/null | sort -hr | head -n 1000
